[metadata]
name = fxdgm
version = attr: 1.1.1
author = Jan Habscheid, Lambert Theisen, Satyvir Singh, Stefanie Braun, Manuel Torrilhon
author_email = Jan.Habscheid@rwth-aachen.de, lambert.theisen@rwth-aachen.de, singh@acom.rwth, braun@acom.rwth, mt@mathcces.rwth-aachen.de
description = A placeholder for the description
long_description = file: README.md
long_description_content_type = text/markdown
url = https://git.rwth-aachen.de/JanHab/fxdgm
keywords = fenics-project, Battery Simulation, finite element method
license = GNU General Public License v3.0 or later
classifiers =
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)
    Programming Language :: Python :: 3

[options]
package_dir=
    =fxdgmfxdgm
packages = find:
zip_safe = True
python_requires >= 3.12
include_package_data = True
install_requires =
    pyvista == 0.43.10
    numpy == 1.26.4
    scipy == 1.14.1

[options.packages.find]
where=fxdgm

[options.entry_points]
console_scripts =
    my-example-utility = example.example_module:main

[options.extras_require]
notebook = jupyter >=1.0.0
tests = pytest == 8.3.3
docs =
    sphinx == 7.3.7
    myst-parser == 4.0.0
    sphinx-copybotton == 0.5.2
    sphinx_rtd_theme == 3.0.1
build = build >= 0.7.0
dev =
    fxdgm[tests]
    fxdgm[docs]
    fxdgm[build]
